import java.util.*;
import java.io.*;

public class Main {
    public static void main(String[] args) throws IOException {
            BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
                    StringTokenizer st = new StringTokenizer(br.readLine());
                            int N = Integer.parseInt(st.nextToken());
                                    int M = Integer.parseInt(st.nextToken());
                                            int[][] g = new int[N][N];
                                                    for (int i = 0; i < N; i++) {
                                                                st = new StringTokenizer(br.readLine());
                                                                            for (int j = 0; j < N; j++)
                                                                                            g[i][j] = Integer.parseInt(st.nextToken());
                                                                                                    }

                                                                                                            int answer = 0;

                                                                                                                    // 모든 중심 (r,c)
                                                                                                                            for (int r = 0; r < N; r++) {
                                                                                                                                        for (int c = 0; c < N; c++) {
                                                                                                                                                        // 모든 크기 K (0부터, 마름모가 격자를 충분히 덮을 때까지)
                                                                                                                                                                        for (int K = 0; K <= 2 * N; K++) {
                                                                                                                                                                                            long cost = (long) K * K + (long)(K + 1) * (K + 1);

                                                                                                                                                                                                                // 비용이 이미 너무 크면(모든 칸이 금이어도 손해) 더 큰 K는 볼 필요 없음
                                                                                                                                                                                                                                    // 최대 가능한 금 개수 = 마름모 칸 수 = cost 자체이므로,
                                                                                                                                                                                                                                                        // cost * M < cost  → M < 1 인 경우만 무의미. 그냥 합으로 판단.

                                                                                                                                                                                                                                                                            int gold = 0;
                                                                                                                                                                                                                                                                                                // |dr| + |dc| <= K 인 칸들
                                                                                                                                                                                                                                                                                                                    for (int dr = -K; dr <= K; dr++) {
                                                                                                                                                                                                                                                                                                                                            int rem = K - Math.abs(dr);
                                                                                                                                                                                                                                                                                                                                                                    for (int dc = -rem; dc <= rem; dc++) {
                                                                                                                                                                                                                                                                                                                                                                                                int nr = r + dr, nc = c + dc;
                                                                                                                                                                                                                                                                                                                                                                                                                            if (nr >= 0 && nr < N && nc >= 0 && nc < N) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            gold += g[nr][nc];   // 격자 밖은 금 없음 → 제외
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        long profit = (long) gold * M;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (profit >= cost) {            // 손해 안 봄
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    answer = Math.max(answer, gold);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    System.out.println(answer);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }